[package]
name = "mednafen-server-rust"
version = "0.1.0"
authors = ["Floogle"]
edition = "2018"

[dependencies]
futures = "0.3.5"
md5 = "0.7.0"
parking_lot = "0.11.0"
rand = "0.7.3"

[dependencies.tokio]
version = "0.2.22"
features = ["full"]